name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Verify build outputs
        run: |
          echo "Checking build outputs..."
          test -f dist/index.js && echo "✅ index.js" || (echo "❌ index.js missing" && exit 1)
          test -f dist/index.mjs && echo "✅ index.mjs" || (echo "❌ index.mjs missing" && exit 1)
          test -f dist/index.d.ts && echo "✅ index.d.ts" || (echo "❌ index.d.ts missing" && exit 1)
          test -f dist/index.d.mts && echo "✅ index.d.mts" || (echo "❌ index.d.mts missing" && exit 1)
          test -f dist/styles.css && echo "✅ styles.css" || (echo "❌ styles.css missing" && exit 1)
          echo "All build files verified successfully!"
      
      - name: Check package size
        run: |
          echo "Package size:"
          du -sh dist
          
      - name: Test package installation
        run: |
          npm pack
          mkdir test-install
          cd test-install
          npm init -y
          npm install ../biomahd-creator-financio-design-system-*.tgz
          echo "✅ Package installation test passed"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.node-version }}
          path: dist/
          retention-days: 7
